### ISSUE TITLE
Docker setup failed (failed to Lchown "" for UID x, GID x)

### ISSUE THREAD

**Issue by purashy** [FoxxMD/multi-scrobbler#96] opened 2023-09-13 17:19 UTC
**Describe the bug**
Whist trying to self-host multi-scrobbler, I receive an error. Pulling and downloading the docker images go well, but it fails at a certain point.

**To Reproduce**
1. create a docker-compose.yaml with below yaml.
2. Deploy.
3. See error

```yaml
version: '3.7'

services:
  multi-scrobbler:
    image: foxxmd/multi-scrobbler
    container_name: multi-scrobbler
    environment:
      - TZ=Cont/TZ
      - SPOTIFY_CLIENT_ID=x
      - SPOTIFY_CLIENT_SECRET=x
      - SPOTIFY_REDIRECT_URI=http://192.168.x.x:9078/callback
      - MALOJA_URL=https://scrobble.local.x.x
      - MALOJA_API_KEY=x
      - PUID=1000
      - PGID=1000
    volumes:
      - /home/syber/multiscrobbler/config:/config
    ports:
      - 9078:9078
    restart: unless-stopped
```

**/etc/subuid:**
`syber:231072:65536`

**/etc/subgid:**
`syber:231072:65536`

**Logs**
> failed to register layer: ApplyLayer exit status 1 stdout: stderr: failed to Lchown "/usr/local/lib/node_modules/patch-package/node_modules/tmp/LICENSE" for UID 2119470584, GID 2042662593 (try increasing the number of subordinate IDs in /etc/subuid and /etc/subgid): lchown /usr/local/lib/node_modules/patch-package/node_modules/tmp/LICENSE: invalid argument

```
failed to deploy a stack: multi-scrobbler Pulling 3f9808342d3e Pulling fs layer b81e0d862760 Pulling fs layer 5eae00e90bd6 Pulling fs layer 852233c4c30e Pulling fs layer 25170e0757ed Pulling fs layer c9cd0f3dbff7 Pulling fs layer 20df4e3daa12 Pulling fs layer b6f0daf554f1 Pulling fs layer 65c0e9591195 Pulling fs layer 4f4fb700ef54 Pulling fs layer 34c345529374 Pulling fs layer 32fba3b3c46c Pulling fs layer 0f9e5cdc96e3 Pulling fs layer 57a0e7bd4bab Pulling fs layer 65c0e9591195 Waiting 4f4fb700ef54 Waiting 34c345529374 Waiting 32fba3b3c46c Waiting 0f9e5cdc96e3 Waiting 57a0e7bd4bab Waiting 852233c4c30e Waiting 25170e0757ed Waiting c9cd0f3dbff7 Waiting 20df4e3daa12 Waiting b6f0daf554f1 Waiting 5eae00e90bd6 Downloading [=====================================&gt; ] 724B/966B 5eae00e90bd6 Downloading [==================================================&gt;] 966B/966B 5eae00e90bd6 Verifying Checksum 5eae00e90bd6 Download complete b81e0d862760 Downloading [========&gt; ] 719B/4.019kB b81e0d862760 Downloading [==================================================&gt;] 4.019kB/4.019kB b81e0d862760 Download complete 3f9808342d3e Downloading [&gt; ] 59.53kB/5.747MB 3f9808342d3e Downloading [====================&gt; ] 2.354MB/5.747MB 3f9808342d3e Downloading [==========================================&gt; ] 4.916MB/5.747MB 3f9808342d3e Download complete 3f9808342d3e Extracting [&gt; ] 65.54kB/5.747MB 3f9808342d3e Extracting [===========&gt; ] 1.376MB/5.747MB 3f9808342d3e Extracting [===================================&gt; ] 4.063MB/5.747MB 3f9808342d3e Extracting [=================================================&gt; ] 5.702MB/5.747MB 3f9808342d3e Extracting [==================================================&gt;] 5.747MB/5.747MB 3f9808342d3e Pull complete b81e0d862760 Extracting [==================================================&gt;] 4.019kB/4.019kB b81e0d862760 Extracting [==================================================&gt;] 4.019kB/4.019kB 25170e0757ed Downloading [===========&gt; ] 733B/3.202kB 25170e0757ed Downloading [==================================================&gt;] 3.202kB/3.202kB 25170e0757ed Verifying Checksum 25170e0757ed Download complete 852233c4c30e Downloading [&gt; ] 46.01kB/4.476MB b81e0d862760 Pull complete 5eae00e90bd6 Extracting [==================================================&gt;] 966B/966B 5eae00e90bd6 Extracting [==================================================&gt;] 966B/966B 852233c4c30e Downloading [===&gt; ] 340.9kB/4.476MB 852233c4c30e Downloading [==========&gt; ] 930.7kB/4.476MB c9cd0f3dbff7 Downloading [&gt; ] 259kB/25.81MB 852233c4c30e Downloading [=======================&gt; ] 2.106MB/4.476MB 5eae00e90bd6 Pull complete 852233c4c30e Downloading [====================================&gt; ] 3.306MB/4.476MB c9cd0f3dbff7 Downloading [===&gt; ] 1.848MB/25.81MB 852233c4c30e Verifying Checksum 852233c4c30e Download complete 852233c4c30e Extracting [&gt; ] 65.54kB/4.476MB c9cd0f3dbff7 Downloading [======&gt; ] 3.188MB/25.81MB 852233c4c30e Extracting [========&gt; ] 786.4kB/4.476MB c9cd0f3dbff7 Downloading [===========&gt; ] 5.834MB/25.81MB 852233c4c30e Extracting [==================================&gt; ] 3.08MB/4.476MB c9cd0f3dbff7 Downloading [================&gt; ] 8.471MB/25.81MB 852233c4c30e Extracting [================================================&gt; ] 4.325MB/4.476MB c9cd0f3dbff7 Downloading [=====================&gt; ] 11.14MB/25.81MB 852233c4c30e Extracting [==================================================&gt;] 4.476MB/4.476MB c9cd0f3dbff7 Downloading [==========================&gt; ] 13.78MB/25.81MB c9cd0f3dbff7 Downloading [===============================&gt; ] 16.43MB/25.81MB c9cd0f3dbff7 Downloading [====================================&gt; ] 19.06MB/25.81MB 852233c4c30e Pull complete c9cd0f3dbff7 Downloading [==========================================&gt; ] 21.7MB/25.81MB 25170e0757ed Extracting [==================================================&gt;] 3.202kB/3.202kB 25170e0757ed Extracting [==================================================&gt;] 3.202kB/3.202kB c9cd0f3dbff7 Downloading [===============================================&gt; ] 24.36MB/25.81MB c9cd0f3dbff7 Verifying Checksum c9cd0f3dbff7 Download complete 20df4e3daa12 Downloading [==================================================&gt;] 190B/190B 20df4e3daa12 Verifying Checksum 20df4e3daa12 Download complete b6f0daf554f1 Downloading [=================================&gt; ] 733B/1.084kB b6f0daf554f1 Downloading [==================================================&gt;] 1.084kB/1.084kB b6f0daf554f1 Verifying Checksum b6f0daf554f1 Download complete 25170e0757ed Pull complete c9cd0f3dbff7 Extracting [&gt; ] 262.1kB/25.81MB c9cd0f3dbff7 Extracting [======&gt; ] 3.146MB/25.81MB c9cd0f3dbff7 Extracting [===========&gt; ] 5.767MB/25.81MB c9cd0f3dbff7 Extracting [=================&gt; ] 8.913MB/25.81MB c9cd0f3dbff7 Extracting [======================&gt; ] 11.8MB/25.81MB c9cd0f3dbff7 Extracting [===========================&gt; ] 14.16MB/25.81MB c9cd0f3dbff7 Extracting [================================&gt; ] 16.78MB/25.81MB 4f4fb700ef54 Downloading [==================================================&gt;] 32B/32B 4f4fb700ef54 Verifying Checksum 4f4fb700ef54 Download complete c9cd0f3dbff7 Extracting [======================================&gt; ] 19.92MB/25.81MB 65c0e9591195 Downloading [&gt; ] 21.13kB/2.078MB c9cd0f3dbff7 Extracting [=========================================&gt; ] 21.5MB/25.81MB 65c0e9591195 Downloading [================&gt; ] 668.6kB/2.078MB 65c0e9591195 Downloading [======================================&gt; ] 1.607MB/2.078MB c9cd0f3dbff7 Extracting [===========================================&gt; ] 22.54MB/25.81MB 65c0e9591195 Verifying Checksum 65c0e9591195 Download complete c9cd0f3dbff7 Extracting [==============================================&gt; ] 23.86MB/25.81MB c9cd0f3dbff7 Extracting [==================================================&gt;] 25.81MB/25.81MB 34c345529374 Downloading [&gt; ] 3.469kB/212.5kB 34c345529374 Downloading [=======================&gt; ] 99.38kB/212.5kB 34c345529374 Verifying Checksum 34c345529374 Download complete 32fba3b3c46c Downloading [==================================================&gt;] 462B/462B 32fba3b3c46c Verifying Checksum 32fba3b3c46c Download complete c9cd0f3dbff7 Pull complete 20df4e3daa12 Extracting [==================================================&gt;] 190B/190B 20df4e3daa12 Extracting [==================================================&gt;] 190B/190B 0f9e5cdc96e3 Downloading [&gt; ] 8.935kB/831.6kB 20df4e3daa12 Pull complete 0f9e5cdc96e3 Verifying Checksum 0f9e5cdc96e3 Download complete b6f0daf554f1 Extracting [==================================================&gt;] 1.084kB/1.084kB b6f0daf554f1 Extracting [==================================================&gt;] 1.084kB/1.084kB b6f0daf554f1 Pull complete 65c0e9591195 Extracting [&gt; ] 32.77kB/2.078MB 65c0e9591195 Extracting [==================================&gt; ] 1.442MB/2.078MB 65c0e9591195 Extracting [===============================================&gt; ] 1.966MB/2.078MB 65c0e9591195 Extracting [==================================================&gt;] 2.078MB/2.078MB 57a0e7bd4bab Downloading [&gt; ] 149.1kB/14.54MB 57a0e7bd4bab Downloading [=&gt; ] 455.6kB/14.54MB 57a0e7bd4bab Downloading [===&gt; ] 1.058MB/14.54MB 57a0e7bd4bab Downloading [========&gt; ] 2.389MB/14.54MB 57a0e7bd4bab Downloading [===============&gt; ] 4.634MB/14.54MB 57a0e7bd4bab Downloading [========================&gt; ] 7.161MB/14.54MB 57a0e7bd4bab Downloading [=================================&gt; ] 9.7MB/14.54MB 57a0e7bd4bab Downloading [==========================================&gt; ] 12.24MB/14.54MB 57a0e7bd4bab Verifying Checksum 57a0e7bd4bab Download complete failed to register layer: ApplyLayer exit status 1 stdout: stderr: failed to Lchown "/usr/local/lib/node_modules/patch-package/node_modules/tmp/LICENSE" for UID 2119470584, GID 2042662593 (try increasing the number of subordinate IDs in /etc/subuid and /etc/subgid): lchown /usr/local/lib/node_modules/patch-package/node_modules/tmp/LICENSE: invalid argument
```

**Versions (please complete the following information):**

- multi-scrobbler: [[v0.5.2](https://github.com/FoxxMD/multi-scrobbler/releases/tag/0.5.2)]
- maloja [[v3.1.5](https://github.com/krateng/maloja/releases/tag/v3.1.5)]

**Comment by FoxxMD** [comment] 2023-09-13 18:02
This looks like an error when using podman, correct? I haven't used podman so I'm not entirely sure what the issue is here. A few things I found:

# UID/GID on container build

https://www.redhat.com/sysadmin/rootless-podman

Under **Allocating additional UIDs/GIDs**:

* make sure you have `newuidmap` and `newgidmap` installed and have allocated ids for your normal user

> for UID 2119470584, GID 2042662593 (try increasing the number of subordinate IDs in /etc/subuid and /etc/subgid

These are IDs are quite high but I don't know if that's abnormal. You can increase the number of IDs available using the instructions found under **Changing the default number of IDs**

# Persisted Data

You may also run into file permission issues once the container is started (or starting) because of how [lsio handles permissions using PUID/PGID](https://docs.linuxserver.io/general/understanding-puid-and-pgid). To fix this you can (probably) do any of the following:

### Use a docker volume instead of mounted directory

```
podman volume create msData
```

In `docker-compose.yaml` under `volumes`:

```
volumes:
      - msData:/config
```

### Use podman uid/gidmaps

Using `podman-compose` [x-podman extension](https://github.com/containers/podman-compose/pull/502) update `docker-compose.yaml`:

```yaml
version: '3.7'

services:
  multi-scrobbler:
  ...
   x-podman:
     uidmaps:
        - "1000:231072:65536"
     gidmaps:
        - "1000:231072:65536"

```

### Set permissions on mounted directory

Based on these resources:

* https://www.reddit.com/r/podman/comments/1229g12/has_anyone_gotten_any_linuxserverio_images_to/
* https://www.smarthomebeginner.com/docker-to-podman-migration-guide/#Linuxserverio_Images
* https://www.smarthomebeginner.com/docker-to-podman-migration-guide/#Environmenal_Variables_in_the_env_File

Set permissions for your config folder based on the PUID and PGID you use:

```
podman unshare chown -R 1000:1000 /home/syber/multiscrobbler/config
```

**Comment by FoxxMD** [comment] 2023-09-13 19:14
> Suprisingly experimental worked.

Glad to hear it.

I use the `experimental` tag for unstable testing so you should not stay on it as-is. You can either:

#### Pin the digest for stable + fix

The image you are currently on is the [stable 0.5.2](https://github.com/FoxxMD/multi-scrobbler/releases/tag/0.5.2) release + fix.

```
foxxmd/multi-scrobbler:experimental@06ac284b257cdbb1b70808dc387f972d0ea2926a5e395d4d5e9569440a597943
```

#### Use `develop` with integrated fix

I've added the fix to the `develop` branch which includes the newest hotness and is my active dev branch that will be released to stable in a week or two. It's very likely to be stable for you but no guarantees.

```
foxxmd/mutli-scrobbler:develop`
```
___

Update your `docker-compose.yml` to use one of those for `image` until the next release is cut.

**Comment by FoxxMD** [comment] 2023-09-13 19:16
@syberslxt can you open a new issue for that error? thanks

**Closed as completed** 2023-09-13 19:53 UTC
Labels: bug
