### ISSUE TITLE
Maloja randomly goes idle and cannot be used

### ISSUE THREAD

**Issue by duckfromdiscord** [FoxxMD/multi-scrobbler#130] opened 2024-01-27 00:50 UTC
**Describe the bug**
Maloja randomly stops scrobbling.

**To Reproduce**
1. Run for an unknown amount of time

**Expected behavior**
Maloja target should start when hitting the "Start" button under "Idle."

**Logs**
It's just this but repeated:
```
2024-01-26T23:02:36+00:00 info    : [Heartbeat] [Clients] Attempted to restart 1 clients that were not processing scrobbles.
2024-01-26T23:02:36+00:00 info    : [Scrobblers] [Maloja - myMaloja] Scrobble processing retries (0) less than max processing retries (5), restarting processing after 3 second delay...
2024-01-26T23:02:36+00:00 error   : [Scrobblers] [Maloja - myMaloja] Cannot read properties of undefined (reading 'data')
TypeError: 
    at t.buildTrackString (CWD/build/server.js:12:93846)
    at m.existingScrobble (CWD/build/server.js:1:40936)
    at m.alreadyScrobbled (CWD/build/server.js:1:63181)
    at m.doProcessing (CWD/build/server.js:1:45857)
    at m.startScrobbling (CWD/build/server.js:1:42873)
    at m.initScrobbleMonitoring (CWD/build/server.js:1:42386)
2024-01-26T23:02:36+00:00 error   : [Scrobblers] [Maloja - myMaloja] Scrobble processing interrupted
2024-01-26T23:02:36+00:00 info    : [Scrobblers] [Maloja - myMaloja] Scrobble processing started
2024-01-26T23:02:36+00:00 info    : [Scrobblers] [Maloja - myMaloja] [Heartbeat] Should be processing scrobbles! Attempting to restart scrobbling...
2024-01-26T22:44:38+00:00 warn    : [Scrobblers] [Maloja - myMaloja] Scrobble processing retries (5) equal to max processing retries (5), stopping processing!
2024-01-26T22:44:38+00:00 error   : [Scrobblers] [Maloja - myMaloja] Cannot read properties of undefined (reading 'data')
```

**Versions (please complete the following information):**
Provide version information for any related sources/clients.

- multi-scrobbler: v0.6.3
- maloja: 3.2.2

**Additional context**
Other times, maloja scrobbling doesn't happen at all but there is no error spam.

**Comment by duckfromdiscord** [comment] 2024-01-27 00:58
It seems after a couple backlog scrobbles this also happens.

```
2024-01-27T00:51:50+00:00 debug   : [Scrobblers] [Maloja - myMaloja] Waiting 363ms to scrobble so time passed since previous scrobble is at least 1000ms
2024-01-27T00:51:51+00:00 info    : [Scrobblers] [Maloja - myMaloja] Scrobbled (Backlog)     => (Spotify) [redacted] @ 2024-01-26T03:25:12+00:00 (C)
2024-01-27T00:51:51+00:00 debug   : [Scrobblers] [Maloja - myMaloja] Raw Payload: [redacted]
2024-01-27T00:51:51+00:00 error   : [Scrobblers] [Maloja - myMaloja] Scrobble processing interrupted
2024-01-27T00:51:51+00:00 error   : [Scrobblers] [Maloja - myMaloja] Cannot read properties of undefined (reading 'data')
TypeError:
    at t.buildTrackString (CWD/build/server.js:12:93846)
    at m.existingScrobble (CWD/build/server.js:1:40936)
    at m.alreadyScrobbled (CWD/build/server.js:1:63181)
    at m.doProcessing (CWD/build/server.js:1:45857)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async m.startScrobbling (CWD/build/server.js:1:42862)
2024-01-27T00:51:51+00:00 info    : [Scrobblers] [Maloja - myMaloja] Scrobble processing retries (0) less than max processing retries (5), restarting processing after 4 second delay...
2024-01-27T00:51:55+00:00 info    : [Scrobblers] [Maloja - myMaloja] Scrobble processing started
2024-01-27T00:51:56+00:00 error   : [Scrobblers] [Maloja - myMaloja] Scrobble processing interrupted
2024-01-27T00:51:56+00:00 error   : [Scrobblers] [Maloja - myMaloja] Cannot read properties of undefined (reading 'data')
```

**Comment by duckfromdiscord** [comment] 2024-01-30 16:41
@FoxxMD I need some kind of workaround for this in the meantime. Around a quarter of my scrobbles are lost because of this and I have to manually scrobble. Could this be fixed by a downgrade?

**Comment by duckfromdiscord** [comment] 2024-01-30 16:42
I also suggest that this error should not cause all scrobbling to stop, because other scrobbles may get through if the error is dropped after a couple retires.

**Comment by FoxxMD** [comment] 2024-01-30 19:05
> Maloja randomly stops scrobbling.

Unless the whole app is silently crashing there is absolutely a reason why it stops scrobbling and it is logged as the entire [scrobble loop is in a try-catch block.](https://github.com/FoxxMD/multi-scrobbler/blob/a1acab0feddad3f1771cbb266418163101400384/src/backend/scrobblers/AbstractScrobbleClient.ts#L617) Please post the logs _before_ it stops scrobbling so I can better help you.

> this error should not cause all scrobbling to stop

The error is showstopping. It is occurs in a function that should not have [any exceptions thrown](https://github.com/FoxxMD/multi-scrobbler/blob/a1acab0feddad3f1771cbb266418163101400384/src/backend/scrobblers/AbstractScrobbleClient.ts#L586) and is occurring because the play information is entirely missing. Continuing execution would be useless because data is likely no longer structured as intended and would only serve to cause more log noise as every queued bad-data-scrobble would throw the same exception. There is a reason it is the way it is.

> some kind of workaround 

I would recommend at the very least updating to the latest version, 0.6.4. If you are still using flatpak I would also recommend [switching to docker installation](https://foxxmd.github.io/multi-scrobbler/docs/installation#docker) because:

* I run spotify -> maloja on my own server and have never experienced any of the long-running issues you are creating
  * There may be problems with flatpak and long-running processes I am not aware of.
* I publish fixes ahead of official releases using docker images because its tremendously easier for me to control for the user's environment and deploy (flatpak is a huge PITA which is why it only gets offical releases) 
  * A potential fix for this is published to `foxxmd/multi-scrobbler:develop` right now

**Comment by duckfromdiscord** [comment] 2024-01-30 20:33
> Please post the logs _before_ it stops scrobbling so I can better help you.

The main reason I haven't been able to do this is because my setup is currently kind of a mess and I don't know how to save logs to a file while they're being printed. Is there an option or some way to automatically log both to the console and also a file? I think if we could do that, I could send more useful logs.

> If you are still using flatpak I would also recommend [switching to docker installation](https://foxxmd.github.io/multi-scrobbler/docs/installation#docker)

Yeah, I'm using flatpak. I would imagine Docker takes more memory (I don't have much available besides what I've already allocated) but perhaps I should try it. I have also noticed I've been having some strange issues that generally haven't happened to you or anyone else. I wonder what causes these. I was originally thinking it could be a discrepancy in the system clock, but that would only explain backlog issues, not issues like this one.

I'll have to try Docker then. Is it possible to move my cache and configuration (in `~/.var/app/io.github.foxxmd.multiscrobbler/[cache,config,etc]`) to Docker?

**Comment by FoxxMD** [comment] 2024-01-30 21:20
This is the memory footprint for MS with an empty config running on my machine in both flatpak and docker:

![image](https://github.com/FoxxMD/multi-scrobbler/assets/4663766/d676667b-ccd7-4a94-bb3d-8c16d1d99341)

The top two processes are flatpak -- 86 + 31 = 117mb
The bottom two processes are docker -- 53 + 17 = 70mb

That doesn't include the memory footprint of docker itself but at least on the application level there is little difference and docker is even lighter than flatpak.

To move your configuration copy the entire folder found at `~/.var/app/io.github.foxxmd.multiscrobbler/config` somewhere else and use that as the [volume mount for `/config`](https://foxxmd.github.io/multi-scrobbler/docs/installation#storage) in the docker container

**Comment by duckfromdiscord** [comment] 2024-01-30 23:13
Impressive. I don't know why I thought docker used more memory than that. I'm not worried anymore. I'll swap to Docker, How does this command sound: `docker run -e "PUID=1000" -e "PGID=1000" -p 9078:9078 -v [configpath]:/config foxxmd/multi-scrobbler:develop`?

**Comment by duckfromdiscord** [comment] 2024-01-31 16:35
I think this issue is solved. I'll run multi-scrobbler for a bit longer, and also try backlog scrobbling, and close the issue if it's solved. I'm using the develop branch on Docker.

**Comment by duckfromdiscord** [comment] 2024-02-08 04:26
I haven't had to try backlog scrobbling yet because multi-scrobbler hasn't crashed since I started using docker 😂

**Comment by FoxxMD** [comment] 2024-02-08 13:49
I added a disclaimer about instability with flatpak installs [to the docs.](https://foxxmd.github.io/multi-scrobbler/docs/installation#flatpak). 

It's honestly disappointing and a little confusing. Flatpak is supposed to be a "batteries included" environment somewhat (but not the same) as docker where your app should "just work" and be sandboxed with its own dependencies etc...there should not be this much variance in behavior between flatpak and docker. MS is only one process, run by node, with very few system calls or dependencies (just writing log files, if enabled). I don't know what could cause it to crash or have such weird behavior that wouldn't also show up in the docker version.  The environment should have very little influence on how it behaves.

On top of that Flatpak is infamously hard to debug. It does not easily output a [stacktrace](https://www.figuiere.net/technotes/notes/tn001/) or decent [debug options](https://github.com/flatpak/flatpak/issues/1464) for the tools it does provide.

**Comment by FoxxMD** [comment] 2024-02-08 17:06
@duckfromdiscord i may have a fix for that issue. please pull the latest `foxxmd/multi-scrobbler:develop` image and restart your MS container

**Comment by duckfromdiscord** [comment] 2024-02-08 22:56
Pulled new image, stopped container, removed it, ran again. Will let you know of results.

**Closed** 2024-02-18 21:40 UTC
